version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000" 
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db 
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ecommerceflow.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped