# Generated by Django 3.2.8 on 2021-10-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'shipping address'},
        ),
    ]
