# Generated by Django 3.2.8 on 2021-10-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20211018_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
