# Generated by Django 3.2.8 on 2021-10-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_modified_at_customer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
