# Generated by Django 3.2.8 on 2021-10-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_notification'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Waiting for payment'), ('failed_payment', 'Failed payment'), ('preparing_shipment', 'Preparing shipment'), ('on_the_way', 'On the way'), ('delivery_refused', 'Returned order'), ('delivered', 'Delivered')], max_length=50)),
                ('observations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('product_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productorder')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit card'), ('cash', 'Cash'), ('bitcoin', 'Bitcoin'), ('paypal', 'Paypal'), ('bank_transfer', 'Bank transfer')], max_length=15)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
            ],
        ),
    ]
