# Generated by Django 3.2.8 on 2021-10-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211015_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='product_order',
        ),
        migrations.AddField(
            model_name='order',
            name='split_payments',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productorder',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.shipping'),
        ),
    ]
