# Generated by Django 3.2.8 on 2021-10-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='', upload_to='categories'),
            preserve_default=False,
        ),
    ]
