# Generated by Django 3.2.8 on 2021-10-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture1',
            field=models.ImageField(default='', upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='picture2',
            field=models.ImageField(default='', upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='picture3',
            field=models.ImageField(default='', upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
